### ISSUE TITLE
sims_sed_library in Photometry/Calculated Magnitudes cannot be downloaded from NCSA anymore

### ISSUE THREAD

**Issue by sylvielsstfr** [lsst/rubin_sim_notebooks#35]
From where could I download these SED. Moreover I would need to use CALSPEC. Could I use PySynphot CALSPEC ?
But in the later case, I have to convert flux per Angstrom into flux per nm.

**Comment by rhiannonlynne** [comment]
The sims_sed_library is now available at 
https://s3df.slac.stanford.edu/data/rubin/sim-data/sed_library/seds_170124.tar.gz 
(the new Rubin data centers, which is now hosting the rubin_sim data directories). 

I haven't tried using CALSPEC myself, but I think if you transformed the values appropriately, it would be fine. (as you say - per angstrom to per nm).
